# Site settings
title: "Francesco Moca"
email: "me@francescomoca.ml"
url: "https://francescomoca.ml"
description: "Full-Stack Developer. Blockchain enthusiast."
meta_author: "Francesco Moca"

about:
  header: About me
  content:
      left: "I am particularly interested in the development of decentralized solutions using peer to peer and blockchain technologies."
      right: "Also interested in machine learning and software development. I have experience developing crossplatform mobile apps and smart contracts as a freelancer."
      bottom: " "
  interests:
    header: Recent Interest 
    content:
      left:
        header: Now
        list:
          - item: Keycloak
          - item: Kubernetes
          - item: Go
      center:
        header: Soon
        list:
          - item: Typescript
          - item: Self Sovereign Identity
          - item: xDai / Matic Network
      right:
        header: "Later (?)"
        list:
          - item: Rust
          - item: Kotlin
          - item: Haskell
  button:
    text: Download My Resume
    href: "/resume/cv_en.pdf"

# Google webmaster tools
google_verify: 

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify: 

# Contact form:
#Â - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname: https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: 

# If you have Google Analytics account setup, enter your tracker ID, eg. A-12312312-1
google_analytics_tracker_id:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 202020 #80B3FF
  primary-rgb: "12,12,12" #"128,179,255"
  secondary-light: 242424 #FD6E8A
  secondary: 0c0c0c #FD6E8A
  secondary-dark: 0a0a0a #A2122F
  blog-text: 222
  link: 1a77bd

# Blog settings
blog:
  labels:
    modal-close: Close

# Markdown/syntax highlighter settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

# Portfolio settings
portfolio:
  labels:
    client: Client
    project-date: Date
    application: Application
    languages: Languages
    concepts: Concepts
    tools: Tools
    stack: Stack
    modal-close: Close

# Footer settings
footer:
  location-header: Location
  location: Milan, Italy
  copyright: Francesco Moca
  social: ""
  new-thoughts: Blog posts

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc. search them in main.css)
social:
  - title: github
    tooltip: "Github"
    url: "https://github.com/franzmoca"
  - title: linkedin
    tooltip: "Linkedin"
    url: "https://www.linkedin.com/in/francesco-moca-69001a121/"


# Credits content
credits:  

# Build settings
permalink: pretty

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
